auth:
  psk:
    enabled: yes
    key: "hello world"

  azureAD:
    enabled: yes
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"    
    # DEV NOTE: in development, we're using the same app for both Azure AD authentication and as an Azure Service Principal. Not recommended in production, however
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"

secretsEncryptionKey: "aQZg30UrCUgu0TfdNvIeLg=="

azure:
  sp:
    tenantId: "1ea3c9a2-b58b-48c7-b5ce-ca311c3c1196"
    clientId: "478f8d4c-d845-478d-bff9-63a0258ee5b1"
    clientSecret: ""
  storage:
    account: "statikocistorage"
  keyVault:
    name: "statiko-ci-akv"
    codesignKey:
      name: "codesign"

nodeName: "e2e-test"
