name = "smplatform"
bin = "bin/smplatform"
vcs = "git"
with_pop = true
with_sqlite = true
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = true
with_grifts = true
as_web = false
as_api = true
